apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: webapp
    type: front-end
spec:
  replicas: 2  # You can change the number of replicas as needed
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          requests:
            memory: "64Mi"  # Minimum memory guaranteed to the container
            cpu: "250m"     # Minimum CPU guaranteed to the container (250 millicores)
          limits:
            memory: "128Mi" # Maximum memory the container can use
            cpu: "500m"    # Maximum CPU the container can use (500 millicores)
      nodeSelector:
        clr: pink