apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pref-deployment
  labels:
    app: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: size
                operator: In
                values:
                - medium
          - weight: 50
            preference:
              matchExpressions:
              - key: size
                operator: In
                values:
                - small
