apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: webapp
    type: front-end
spec:
  replicas: 3  # Number of pod replicas
  selector:
    matchLabels:
      app: webapp
      type: front-end
  template:
    metadata:
      labels:
        app: webapp
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: size
                    operator: In
                    values:
                      - medium
                      - small
