# apiVersion: v1
# kind: Service
# metadata:
#   name: swiggy-app
#   labels:
#     app: swiggy-app
# spec:
#   type: LoadBalancer
#   ports:
#   - port: 80
#     targetPort: 80
#   selector:
#     app: swiggy-app


#addded for test
apiVersion: v1
kind: Service
metadata:
  name: my-k8s-service
spec:
  selector:
    app: my-k8s-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
